// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHi2kRAwwXzqlVn7VapzSJC-llFOqGTY',
    appId: '1:192319556201:android:fee6939dc3e686806970f8',
    messagingSenderId: '192319556201',
    projectId: 'finlitt-cb9cb',
    databaseURL: 'https://finlitt-cb9cb-default-rtdb.firebaseio.com',
    storageBucket: 'finlitt-cb9cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJHI7nhIhEOYytVUgfumRa4UQsH1uNenA',
    appId: '1:192319556201:ios:9255eceabe0c65636970f8',
    messagingSenderId: '192319556201',
    projectId: 'finlitt-cb9cb',
    databaseURL: 'https://finlitt-cb9cb-default-rtdb.firebaseio.com',
    storageBucket: 'finlitt-cb9cb.appspot.com',
    iosClientId: '192319556201-gdnguts1okuok0g0d64e1erobob2uc4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.finlittGdsc',
  );
}
